language: android

jdk:
- oraclejdk8

env:
  global:
  - ANDROID_TARGET=android-15
  - ANDROID_ABI=armeabi-v7a

notifications:
  slack: applivery:KX1jJ5dWdGbw0xXOXImfKgSD#ci

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
  - extra-android-support
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-19
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- pip install --user codecov

script:
- ./gradlew build jacocoTestReport
- ./gradlew check

after_success:
- ./gradlew jacocoFullReport
- codecov
- bash <(curl -s https://codecov.io/bash)


